package br.ufes.inf.lprm.context.model;

import java.util.List;
import java.util.Set;
import java.util.HashSet;

rule ContextValue
when
    $update: ContextValue()
    $context: IntrinsicContext(UID == $update.contextUID)
then
    $context.setValue($update.getValue());
    update($context);
end

rule RelationalContextUpdate
when
    $update: ContextValue()
    $context: RelationalContext(UID == $update.contextUID)
then
    $context.setValue($update.getValue());
    update($context);
end