package co.pextra.scenarios.SensitiveProductStorage;

import java.util.List;
import java.util.Date;
import co.pextra.model.*
import java.util.ArrayList
import java.lang.Double

rule EstimateTimeOfArrivalUpdate
    no-loop
    when
        person: Person()
        container: Container(owner == person)
        eta: EstimateTimeOfArrival(watcher == person, target == container)
        Location(bearer == person, pl: value)
        Location(bearer == container, cl: value)
        Speed(bearer == person, ps: value)
    then
        double distance = Location.distance(pl, cl);
        eta.setValue(new Date((long) (distance / ps)));
        // TODO: gambiarra
        delete(eta);
        insert(eta);
    end