package co.pextra.scenarios.SensitiveProductStorage;

import java.util.List;

import br.ufes.inf.lprm.scene.model.Situation;
import br.ufes.inf.lprm.situation.bindings.*;
import br.ufes.inf.lprm.situation.model.Participation;
import br.ufes.inf.lprm.situation.model.SituationType
import br.ufes.inf.lprm.scene.util.SituationHelper;

/*declare ETABiggerThanTTT extends Situation
  eta: EstimateTimeOfArrival @part @key
  //ttt: TimeToThreshold @part @key
end*/

rule ETABiggerThanTTT
 //@role(situation) @type(ETABiggerThanTTT)
  when
    //person: Person()
    //batch: Batch(owner == person)
    //ttt: TimeToThreshold(bearer == batch)
    ttt: TimeToThreshold()
    //eta: EstimateTimeOfArrival(bearer == person)
    //eta: EstimateTimeOfArrival()
  then
    System.out.println("-------------------------------------------- ETABiggerThanTTT");
    //SituationHelper.situationDetected(drools);
end

